---
- name: Create nextcloud app
  shell: "dokku apps:create {{ app_name }} || true"
  ignore_errors: true

- name: Create PostgreSQL service
  shell: "dokku postgres:create {{ pg_service_name }}"
  ignore_errors: true

- name: Link PostgreSQL service to nextcloud app
  shell: "dokku postgres:link {{ pg_service_name }} {{ app_name }}"
  ignore_errors: true

- name: Create Redis service
  shell: "dokku redis:create {{ redis_service_name }}"
  ignore_errors: true

- name: Link Redis service to nextcloud app
  shell: "dokku redis:link {{ redis_service_name }} {{ app_name }}"
  ignore_errors: true

- name: Get Redis environment variables to config NextCloud
  script: ../redis_envvars.sh

- name: Deploy NextCloud from Docker image
  shell: "dokku git:from-image {{ app_name }} nextcloud:production"
  ignore_errors: true

- name: Set app domain
  shell: "dokku domains:add {{ app_name }} {{ app_domain }}"
  ignore_errors: true

- name: Config Let's Encrypt
  shell: "dokku config:set {{ app_name }} DOKKU_LETSENCRYPT_EMAIL={{ admin_email }}"
  ignore_errors: true

- name: Create and mount storage volumes
  shell: "mkdir -p {{ data_path }}/{{ item }}"
  shell: "chown www-data:www-data {{ data_path }}/{{ item }}"
  shell: "dokku storage:mount {{ app_name }} "{{ data_path }}/{{ item }}:/var/www/html/{{ item }}""
  loop:
    - config
    - custom_apps
    - data
  ignore_errors: true

- name: Restart NextCloud app
  shell: "dokku ps:restart {{ app_name }}"





































