---
- name: Create app
  dokku_app:
    app: "{{ app_name }}"

- name: Disable the zero downtime deployment
  dokku_checks:
    app: "{{ app_name }}"
    state: absent

- name: domains:add "{{ app_name }}" "{{ app_domain }}"
  dokku_domains:
    app: "{{ app_name }}"
    domains:
      - "{{ app_domain }}"

- name: environment configuration
  dokku_config:
    app: "{{ app_name }}"
    config:
      DOKKU_LETSENCRYPT_EMAIL: "{{ admin_email }}"

#- name: Enable the letsencrypt plugin
#  dokku_letsencrypt:
#    app: "{{ app_name }}"

- name: postgres:create "{{ pg_service_name }}"
  dokku_service_create:
    name: "{{ pg_service_name }}"
    service: postgres

- name: postgres:link "{{ pg_service_name }}" "{{ app_name }}"
  dokku_service_link:
    app: "{{ app_name }}"
    name: "{{ pg_service_name }}"
    service: postgres

- name: redis:create "{{ redis_service_name }}"
  dokku_service_create:
    name: "{{ redis_service_name }}"
    service: redis

- name: redis:link default "{{ app_name }}"
  dokku_service_link:
    app: "{{ app_name }}"
    name: "{{ redis_service_name }}"
    service: redis

- name: Get Redis environment variables to config NextCloud
  script: ../redis_envvars.sh

- name: Pull and deploy Nextcloud
  dokku_image:
      app: "{{ app_name }}"
      image: nextcloud:production

- name: mount volume paths
  dokku_storage:
    app: "{{ app_name }}"
    mounts:
      - "{{ data_path }}/{{ item }}:{{ app_docroot }}{{ item }}"
    create_host_dir: true
  loop:
    - config
    - custom_apps
    - data

- name: proxy:ports-clear "{{ app_name }}"
  dokku_ports:
    app: "{{ app_name }}"
    state: clear

- name: Restart NextCloud app
  shell: "dokku ps:restart {{ app_name }}"
