---
- name: Create nextcloud app
  shell: "dokku apps:create {{ app_name }} || true"
  ignore_errors: true

- name: Create PostgreSQL service
  shell: "dokku postgres:create {{ pg_service_name }}"
  ignore_errors: true

- name: Link PostgreSQL service to nextcloud app
  shell: "dokku postgres:link {{ pg_service_name }} {{ app_name }}"
  ignore_errors: true

- name: Create Redis service
  shell: "dokku redis:create {{ redis_service_name }}"
  ignore_errors: true

- name: Link Redis service to nextcloud app
  shell: "dokku redis:link {{ redis_service_name }} {{ app_name }}"
  ignore_errors: true

- name: Get Redis environment variables to config NextCloud
  script: ../redis_envvars.sh
